# Generated by Django 4.1.3 on 2022-12-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_alumnos_alumno_rename_profesores_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fotoPerfilUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
