# Generated by Django 4.1.3 on 2022-12-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_alumno_fotoperfilurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='horasClase',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='numeroEmpleado',
            field=models.IntegerField(),
        ),
    ]
